### ISSUE TITLE
can not replicate, could you please help me, thanks.

### ISSUE THREAD

**Issue by liamxg** [nrennie/tidytuesday#1]
df <- df %>% drop_na(c("country", "start_year", "end_year", "cost_km_millions"), any_of(vars))
Error: Must subset columns with a valid subscript vector.
x Subscript has the wrong type `function`.
ℹ It must be numeric or character.

**Comment by nrennie** [comment]
Drop the anyof(vars) argument from drop_na, it should work. Code updated.

**Comment by liamxg** [comment]
thanks for your help.

**Comment by liamxg** [comment]
img <- image_read("bg.jpg")  where to find bg.jpg, thanks @nrennie

**Comment by nrennie** [comment]
Can you please be a bit more specific - there's hundreds of files in this repository and you haven't mentioned which one is causing the error?

As a general rule, I don't upload images to GitHub that I don't own the rights to, so at best I can link you to the image's source.
